on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo 
    - uses: actions/checkout@master
      
    - name: npm install, build, and test
      run: |
        cd ./app-sample
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with:
        publish-profile: ${{ secrets.nodesa_publishprofile }}
        package: ./app-sample
